#!/bin/sh
#
# An hook script to prepare a packed repository for use over dumb transports.
#

curl --user admin:abe5fc484716c5b08f37dcff045e7d7c http://localhost:8080/job/Hello-Worl

/home/ec2-user/Hello-World/buildExecutable

echo "============================== This is from Hello World demo post-commit ============================== "


